/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica_1.Front;

import com.mycompany.practica_1.Reportes.Errores;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cheji
 */
public class ReporteError extends javax.swing.JFrame {

    /**
     * Creates new form ReporteError
     */
    public ReporteError() {
        initComponents();
    }
    
    public void AgregarErrores(LinkedList<Errores> err){
        DefaultTableModel modelo = (DefaultTableModel) tblErrores.getModel();
        int filas = err.size();
        modelo.setRowCount(filas);
        for (int i = 0; i < filas; i++) {
            modelo.setValueAt(err.get(i).getFila(), i, 0);
            modelo.setValueAt(err.get(i).getColumna(), i, 1);
            modelo.setValueAt(err.get(i).getError(), i, 2);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblErrores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fila", "Columna", "Error", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblErrores);
        if (tblErrores.getColumnModel().getColumnCount() > 0) {
            tblErrores.getColumnModel().getColumn(0).setResizable(false);
            tblErrores.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblErrores.getColumnModel().getColumn(1).setResizable(false);
            tblErrores.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblErrores.getColumnModel().getColumn(2).setResizable(false);
            tblErrores.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("REPORTE DE ERRORES ENCONTRADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblErrores;
    // End of variables declaration//GEN-END:variables
}
