/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica_1.Front;

import com.mycompany.practica_1.Reportes.Colores;
import com.mycompany.practica_1.Reportes.Errores;
import com.mycompany.practica_1.Reportes.Figuras;
import com.mycompany.practica_1.Reportes.Operadores;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cheji
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOperaciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblColores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFiguras = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAnimaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Salida(evt);
            }
        });

        tblOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Operador", "Linea", "Columna", "Operacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOperaciones);
        if (tblOperaciones.getColumnModel().getColumnCount() > 0) {
            tblOperaciones.getColumnModel().getColumn(0).setResizable(false);
            tblOperaciones.getColumnModel().getColumn(1).setResizable(false);
            tblOperaciones.getColumnModel().getColumn(1).setHeaderValue("Linea");
            tblOperaciones.getColumnModel().getColumn(2).setHeaderValue("Columna");
            tblOperaciones.getColumnModel().getColumn(3).setResizable(false);
        }

        tblColores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Color", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblColores);
        if (tblColores.getColumnModel().getColumnCount() > 0) {
            tblColores.getColumnModel().getColumn(0).setResizable(false);
            tblColores.getColumnModel().getColumn(1).setResizable(false);
            tblColores.getColumnModel().getColumn(1).setHeaderValue("Linea");
        }

        jLabel1.setText("OPERACIONES");

        jLabel2.setText("COLORES USADOS");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("FIGURAS USADAS");

        tblFiguras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Figura", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblFiguras);
        if (tblFiguras.getColumnModel().getColumnCount() > 0) {
            tblFiguras.getColumnModel().getColumn(0).setResizable(false);
            tblFiguras.getColumnModel().getColumn(1).setResizable(false);
            tblFiguras.getColumnModel().getColumn(1).setHeaderValue("Linea");
        }

        jLabel4.setText("MOVIMIENTOS USADOS");

        tblAnimaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Movmmiento", "Cantidad Uso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblAnimaciones);
        if (tblAnimaciones.getColumnModel().getColumnCount() > 0) {
            tblAnimaciones.getColumnModel().getColumn(0).setResizable(false);
            tblAnimaciones.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Salida(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Salida
        this.setVisible(false);
    }//GEN-LAST:event_Salida

    public void AgregarDatos(LinkedList<Operadores> op, LinkedList<String> fig, LinkedList<String> movi, LinkedList<String> clrs){
        DefaultTableModel modelo = (DefaultTableModel) tblOperaciones.getModel();
        int filas = op.size();
        modelo.setRowCount(filas);
        for (int i = 0; i < filas; i++) {
            modelo.setValueAt(op.get(i).tipo(), i, 0);
            modelo.setValueAt(op.get(i).fila(), i, 1);
            modelo.setValueAt(op.get(i).colum(), i, 2);
            modelo.setValueAt(op.get(i).operacion(), i, 3);
        }
        
        DefaultTableModel modelo1 = (DefaultTableModel) tblColores.getModel();
        filas = clrs.size();
        modelo1.setRowCount(filas);
        for (int i = 0; i < filas; i++) {
            modelo1.setValueAt(clrs.get(i), i, 0);
            modelo1.setValueAt(Colores.getCant(clrs.get(i)), i, 1);
        }
        
        DefaultTableModel modelo2 = (DefaultTableModel) tblFiguras.getModel();
        filas = fig.size();
        modelo2.setRowCount(filas);
        for (int i = 0; i < filas; i++) {
            modelo2.setValueAt(fig.get(i), i, 0);
            modelo2.setValueAt(Figuras.getCant(fig.get(i)), i, 1);
        }
        
        DefaultTableModel modelo3 = (DefaultTableModel) tblAnimaciones.getModel();
        filas = movi.size();
        modelo3.setRowCount(filas);
        for (int i = 0; i < filas; i++) {
            modelo3.setValueAt(movi.get(i), i, 0);
            modelo3.setValueAt(Movimientos.getCant(movi.get(i)), i, 1);
        }
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAnimaciones;
    private javax.swing.JTable tblColores;
    private javax.swing.JTable tblFiguras;
    private javax.swing.JTable tblOperaciones;
    // End of variables declaration//GEN-END:variables
}
