
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.practica_1.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 14;
  public static final int FLOTANTES = 3;
  public static final int PARCLS = 20;
  public static final int SUMA = 5;
  public static final int PAROPN = 19;
  public static final int MULTI = 7;
  public static final int CURVA = 13;
  public static final int ANIMAR = 16;
  public static final int COLOR = 4;
  public static final int CUADRADO = 10;
  public static final int OBJETO = 17;
  public static final int ID = 22;
  public static final int GRAFICAR = 15;
  public static final int COMA = 21;
  public static final int DIVISN = 8;
  public static final int NUMEROS = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int POLIGONO = 12;
  public static final int CIRCULO = 9;
  public static final int ANTERIOR = 18;
  public static final int RECTANGULO = 11;
  public static final int RESTA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMEROS",
  "FLOTANTES",
  "COLOR",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVISN",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "POLIGONO",
  "CURVA",
  "LINEA",
  "GRAFICAR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "PAROPN",
  "PARCLS",
  "COMA",
  "ID"
  };
}

